# Generated by Django 4.2.5 on 2023-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(choices=[('', 'Choose Product Unit'), ('kg', 'kg'), ('l', 'litre'), ('pcs', 'pcs'), ('gm', 'gm'), ('m2', 'm2'), ('m3', 'm3'), ('ml', 'ml')], default='', max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tbl_products',
            },
        ),
    ]
